# Common vars
availability_zone: melbourne-qh2-uom
instance_image: 356ff1ed-5960-4ac2-96a1-0c0198e6a999
instance_key_name: harry_Ubuntu
instance_flavor: uom.mse.2c9g

# Volumes
volumes:
  - vol_name: couch-vol-1-docker
    vol_size: 10
  - vol_name: couch-vol-1-data
    vol_size: 70
  - vol_name: couch-vol-2-docker
    vol_size: 10
  - vol_name: couch-vol-2-data
    vol_size: 70
  - vol_name: couch-vol-3-docker
    vol_size: 10
  - vol_name: couch-vol-3-data
    vol_size: 70
  - vol_name: flask-vol
    vol_size: 10
# Security groups
security_groups:
  - name: icmp
    description: "Allow pings to instances"
    protocol: icmp
    port_range_min: 8
    port_range_max: -1
    remote_ip_prefix: 0.0.0.0/0
  - name: ssh
    description: "Allow universal SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: http
    description: "Allow universal HTTP access"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
  - name: cluster
    description: "Allow node with cluster security group access"
    protocol: any
    port_range_min: -1
    port_range_max: -1
    remote_group: cluster
#  - name: docker_management
#    description: "docker cluster management communications"
#    protocol: tcp
#    port_range_min: 2377
#    port_range_max: 2377
#    remote_ip_prefix: 0.0.0.0/0
#  - name: docker_nodes_tcp
#    description: "docker communication among nodes"
#    protocol: tcp
#    port_range_min: 7946
#    port_range_max: 7946
#    remote_ip_prefix: 0.0.0.0/0
#  - name: docker_nodes_udp
#    description: "docker communication among nodes"
#    protocol: udp
#    port_range_min: 7946
#    port_range_max: 7946
#    remote_ip_prefix: 0.0.0.0/0
#  - name: docker_overlay
#    description: "docker overlay network traffic"
#    protocol: udp
#    port_range_min: 4789
#    port_range_max: 4789
#    remote_ip_prefix: 0.0.0.0/0
#  - name: couchdb
#    description: "couchdb"
#    protocol: tcp
#    port_range_min: 5984
#    port_range_max: 5984
#    remote_ip_prefix: 0.0.0.0/0
#  - name: couchdb_erlang
#    description: "couchdb"
#    protocol: tcp
#    port_range_min: 4369
#    port_range_max: 4369
#    remote_ip_prefix: 0.0.0.0/0
#  - name: couchdb_range
#    description: "couchdb"
#    protocol: tcp
#    port_range_min: 9100
#    port_range_max: 9200
#    remote_ip_prefix: 0.0.0.0/0
# Instances
instances:
  - name: couch-server-1
    volumes: ['couch-vol-1-docker', 'couch-vol-1-data']
  - name: couch-server-2
    volumes: ['couch-vol-2-docker', 'couch-vol-2-data']
  - name: couch-server-3
    volumes: ['couch-vol-3-docker', 'couch-vol-3-data']
  - name: flask-server
    volumes: ['flask-vol']