# Common vars
availability_zone: melbourne-qh2-uom
instance_image: 356ff1ed-5960-4ac2-96a1-0c0198e6a999
instance_key_name: id_rsa
instance_flavor: uom.mse.2c9g

# Volumes
volumes:
  - vol_name: couch-vol-1-data
    vol_size: 70
  - vol_name: couch-vol-2-data
    vol_size: 70
  - vol_name: couch-vol-3-data
    vol_size: 70
# Security groups
security_groups:
  - name: icmp
    description: "Allow pings to instances"
    protocol: icmp
    port_range_min: 8
    port_range_max: -1
    remote_ip_prefix: 0.0.0.0/0
  - name: ssh
    description: "Allow universal SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: http
    description: "Allow universal HTTP access"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
  - name: http
    description: "Allow access to couchdb"
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0
  - name: cluster
    description: "Allow node with cluster security group access"
    protocol: any
    port_range_min: -1
    port_range_max: -1
    remote_group: cluster
# Instances
instances:
  - name: couch-server-1
    volumes: ['couch-vol-1-data']
  - name: couch-server-2
    volumes: ['couch-vol-2-data']
  - name: couch-server-3
    volumes: ['couch-vol-3-data']
  - name: flask-server
    volumes: []