---
- name: Gather facts of remote host
  ansible.builtin.setup:
    gather_subset: all

- name: Wait for sudo
  become: yes
  ansible.builtin.shell: while sudo fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 5; done;

- name: Install dependencies
  tags: always
  become: yes
  ansible.builtin.apt:
    name: ['apt-transport-https', 'build-essential', 'ca-certificates', 'curl', 'git', 'python3-dev', 'python3-pip', 'python3-setuptools', 'software-properties-common', 'unzip', 'vim']
    state: latest
    install_recommends: no
    update_cache: yes
    lock_timeout: 300

- name: Update pip
  tags: always
  become: yes
  ansible.builtin.pip:
    name: ['pip']
    state: latest