---
#- name: Create Couchdb directory
#  become: yes
#  ansible.builtin.file:
#    path: "{{ couchdb_dir }}"
#    owner: "{{ ansible_user }}"
#    group: "{{ ansible_user }}"
#    recurse: yes
#    state: directory
- name: IP Address
  set_fact:
    IpAdd: "{{ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0])}}"

- name: Configure compose
  become: yes
  ansible.builtin.template:
    src: docker-compose.yaml.j2
    dest: "{{ couchdb_dir }}/docker-compose.yaml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Run docker compose
  become: yes
  community.docker.docker_compose:
    project_src: "{{ couchdb_dir }}"
    pull: yes
    state: present
    remove_orphans: yes
    recreate: always

