---
# Create an instance on the MRC with logins for every required user
- name: Create an instance
  openstack.cloud.server:
    name: '{{ item.name }}'
    image: '{{ instance_image }}'
    key_name: '{{ instance_key_name }}'
    flavor: '{{ instance_flavor }}'
    availability_zone: '{{ availability_zone }}'
    security_groups: '{{ sg_names }}'
    volumes: '{{ item.volumes }}'
    auto_floating_ip: yes
    wait: yes
    timeout: 600
    state: present
    userdata: |
      #cloud-config
      users:
          - default
          - name: harry
            shell: /bin/bash
            sudo: ALL=(ALL) NOPASSWD:ALL
            groups: users, admin
            lock_passwd: true
            ssh_authorized_keys:
              - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC45wDiP8hxKD7gOvZ2K4zc+HJZiQOaR6yyQ4V43FeVxzTdgSQiuNOCHnL9GJzAmlugcrSjDYULxzoo1+/ZtMCW0qWostYCQjc5tr/yaSHwJMI1ZXFZnc4iqj8QfzKR8eN9bqcHt/plfy9FboobPW7JR/ANMqTk8A9GAqzyXWjRu059QgmxxBJeEUWXys1wwbpbBdhUjLC1eaNryT4wYFKpJpIKfoorVIjzQ1+eZUOzpnDgwLFmg+RijFOjEQwogwD83Fl+N+LgbWbeUI3tjqrVrSI0v9CarF7NboRMJRvs+kB7D6xqNmYl/6GUTUl9tD/Zz26g/jicQbXmPpX7gdW5gzrQ7Z6/zEDZSYhAvbiFEksls03cW3JrqZKwqdEErKARE6jDowhX9NobNkM7//KN5vMc6MkgqPjH9GM40Q3YlbSERudFmSdOadDWIdqEPsWbjcOSFr3dsmrWxMTSs4MnzrpbNybAFKwJlorG0vmZMnd6T3WDIYYhlTjBrZoR64sS3hyGmQfv+LZfTJ+B6i4uTbvi8/V6vBw8SbcVc7u3IRtqEG3POg4GpUOuzdc+tU24pza7vncP7Zpz2Q5Drq80Xp8zkSXCYR1RyC2gLbHz8elSzpXCm3vcVbKRHUp8khaQwe0Py5zNfyO9W9NGLbcTXZYgzkkYcB+x6EkPIwndtw== luongvd3@gmai.com
          - name: james
            shell: /bin/bash
            sudo: ALL=(ALL) NOPASSWD:ALL
            groups: users, admin
            lock_passwd: true
            ssh_authorized_keys:
              - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDquRNlqrtre8fc4L22N0EkaQmFMlt2/ovEY7W+b67Ov5KYN8DyDA1Iyqz2hgh2yYltY2WBDqJa6hrDKl2G6hJ8wjOrkqmIF1Y6412ZpM5SWyqOPUE3B5VKp9Ybb43hC/7r6Kux0DND7+y6R1rRIcByZo/Tb+REDLXxKlCfigIUScYI0vhY8O6z2oEWtHenc+NrDQhbdJh2CQW2ks6VSawAakU0xwaDfDvy6Bzamy1/xNTTVD99jCMyUoxKzp76kKj3L2w5ZnVuQE5kBOyxWpPtB0h54qEP4Wd5YwOKImyBXs4CLCagwFa9ETbdIRCd/qeO36obYLQsM87aYLNTpPFXVWRmNfAEal+TSdZU12Ua+6bO5fVQziOEG5+3URe/dpdHAXQSF3JTewtAqKwWq9MEhLcI4td0zqAFBvFqkJum2nJQwMOpk3/IQuFyOjFlNiUNDniS9MTGNmu9SGjLSKiwY04rcFSM9VH59TrycHlU8cvGNRfXeuP9HzUzctFKMV0= jkerlidis@DESKTOP-HJ38CHK
          - name: tom
            shell: /bin/bash
            sudo: ALL=(ALL) NOPASSWD:ALL
            groups: users, admin
            lock_passwd: true
            ssh_authorized_keys:
              - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDO7vuNrB13GN9TO4IQZA7jxy8mQooNUKFnDdJgkZ05rT+qP3GFLy1rvLW/UwQPHkfd6eNutGHIxmvZu0uIX1OdcEKlyN0Gyzt//ZY17SEVWMDeoKbU3brMXiyn23hOgWCqs3a1/whh90UUVprjoXE8K1Ms+3R+PfV5INSHpc/6nL9mgkVc4uSAw6JsnByxUws4495g5BaiKIBLZ+Gwa00XpPrXsrAhjOWwKzjDni0/gtLerZ2pEKugtj1wu3k0eHx+O1z8qoqd6iQjqiYNY8gb/mGoyv8BCdxOo5AhEq66aphnubMt/j4+ytwa3rqQ6kemh7SM8ztET4KgAXz7ftZj Generated-by-Nova
          - name: zack
            shell: /bin/bash
            sudo: ALL=(ALL) NOPASSWD:ALL
            groups: users, admin
            lock_passwd: true
            ssh_authorized_keys:
              - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCs7Ms/hR9WRnjgmu+e4BDb3at8uDKxNuAgXAlVSFd2aqhCt3VAMoBVnAWpWqaQnEquSICqU7OBEf7iT32ftHwWVFt6tDnZdURJycdSTW678yAyeTCHMiF9axyhVxaAd54J8947xprG1qpvUFiV+3pccMgbzBfsSwU0yCH+f9hEo49Z6A2njQsYM4w5oXxowayPZwpnevz79goaRK1kBG2A61QkNnml4+uDRoGLMSlqoRadEnFviUnLRg2zlQ2bmkmakgJ1DjNGMQ1B3OdTlujSA2xJgDqQZhcRt1ci0i/okBu7IZJ7KMXTz2YUSbfOm1LYXWB6/bdwzMOpEB9xJlVX Generated-by-Nova
          - name: julius
            shell: /bin/bash
            sudo: ALL=(ALL) NOPASSWD:ALL
            groups: users, admin
            lock_passwd: true
            ssh_authorized_keys:
              - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDcUctfqr5d5fqtgRaiWCeBNF2k6CZuxj5d2tVypCy9SMPFui0G0AqFjOPikWnfwKIaDeKQ+fOaT3qQmgdNAF2BsTpvACaKHc8INNLILQgTiK8Igj1NLqn/o2lVP4kDgDpxqKLKFS+vHmbJ4HJ4AL/V2ov3pR89KnhCgt1X7vbiQg1LDMqEQ1ZGAoR9cOwB0vQBHxKfTBiv+vAW5R3auc1pUA9X86md1lbr4TzSgt1mRRYfjrEbOpY+o5VAXxPMQrVAFCYbEEmYVlNq015fKERqM1NW1NbXrPYyKEW/8OIwjEGb6T7kG7qZNrb66hx6iJwDKMPasB83tb6o82hFi7JT Generated-by-Nova

  loop: '{{ instances }}'
  register: os_instance

- ansible.builtin.debug:
    msg: "Instance {{ item.openstack.name }} has been created. IP address is {{ item.openstack.public_v4 }}"
  loop: '{{ os_instance.results }}'
  when: item.openstack is defined

- name: Wait for connection
  ansible.builtin.wait_for:
    host: "{{ item.openstack.public_v4 }}"
    port: 22
    timeout: 120
    search_regex: OpenSSH
  loop: '{{ os_instance.results }}'
  when: item.openstack is defined

# Add hosts to Ansible in-memory inventory
- name: Add couchdb hosts
  ansible.builtin.add_host:
    name: '{{ item.openstack.public_v4 }}'
    groups: couchdb
  loop: '{{ os_instance.results[:3] }}'
  when: item.openstack is defined

- name: Add flask host
  ansible.builtin.add_host:
    name: '{{ os_instance.results[3].openstack.public_v4 }}'
    groups: flask
  when: os_instance.results[3].openstack is defined